### PR TITLE
I had to do this to build on windows

### PR DESCRIPTION
**Pull request by gougeon-s**
I was able to build binmap.exe with these changes but I couldn't build blobmap
Changes in the README.rst are mostly for the python libs

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Can you elaborate on the

>  but I couldn't build blobmap

problem? Is it solve with this issue?

**Comment by gougeon-s** [comment]
No, I couldn't built anything before the change in CMakeLists.txt. Then I was able to build binmap.exe. I still can't build blobmap

**Comment by serge-sans-paille** [comment]
I successfully pushed appveyor integration without the need of this patch.
Can you try current master version, using a setup similar to the one in

    https://github.com/quarkslab/binmap/blob/master/appveyor.yml

**Comment by gougeon-s** [comment]
Actually I moved from home for 6 months. I don't have any windows with me so I won't be able to test. But if it is working we may just delete this PR. It could be a good idea to have this link on the README

**Pull request closed without merging**
